import Head from "next/head";
//COMPONENTS and PAGES
import Header from "../components/Header";
import Feed from "../components/Feed";
import Modal from "../components/Modal";
//recoil
import { useRecoilValue } from "recoil";
import { modalState } from "../atoms/modelAtom";
export default function Home() {
  const open = useRecoilValue(modalState);
  return (
    <div>
      <Head>
        <title>Instagram Clone..</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* SKETCHING THE BUILD...
      Header done
      Feed done
      Modal */}
      <Header />
      <Feed />
      <Modal />
    </div>
  );
}
