import Head from "next/head";
//COMPONENTS and PAGES
import Header from "../components/Header";
import Feed from "../components/Feed";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Instagram Clone..</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* SKETCHING THE BUILD...
      Header 
      Feed 
      Modal */}
      <Header />
      <Feed />
    </div>
  );
}
